name: meuDeploy para paginas do Github

on:
 push:
    branches:
        - main
    
    permissions: 
    contents: write
    pages: write
    id-token: write
    
jobs:
  deploy:
     runs-on: ubuntu-latest

  steps:
     - name: Checkout do repositorio
       uses: actions/checkout@v4

     - name: Configurar Github Pages
       uses: actions/configure-pages@v5

     - name: Criar artefatos para meuDeploy
       uses: actions/upload-pages-artifact@v3
       with: 
         path: -

      - name: Publica no GitPages
        uses: actions/deploy-pages@v4
      
